apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  # only run 1 instance of the pod:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    # list all containers inside this pod:
    spec:
      containers:
        - name: client
          image: rallycoding/client-99
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    # service should manage pods with this label:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
